import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    type: 'Dash',
    initiative: 'Projeto App de Gestão',
    code: 'C00014',
    name: 'Funil de Vendas',
    phase: 'Desenvolvimento',
    status: 'Em andamento',
    baseline: 'A definir',
    report: 'Previsão de entrega da 1ª versão – entre 02 e 06/03',
    farol: 'No prazo',
  },
  {
    id: '2',
    type: 'Dash',
    initiative: 'Projeto App de Gestão',
    code: 'C00036',
    name: 'Dash Gestão Varejo',
    phase: 'Homologação Cliente',
    status: 'Em andamento',
    baseline: 'A definir',
    report: 'Entregue para validação do cliente 13/02',
    farol: 'No prazo',
  },
  {
    id: '3',
    type: 'Melhoria',
    initiative: 'Combo Multi',
    code: 'C00003.12',
    name: 'Divergência resposta crédito SIV x Netsales',
    phase: 'Escopo',
    status: 'Em andamento',
    baseline: 'A definir',
    report: 'Em análise para possível abertura de projeto interno Claro.',
    farol: 'No prazo',
  },
  {
    id: '4',
    type: 'Melhoria',
    initiative: 'Combo Multi',
    code: 'C00003.13',
    name: 'Divergência de credito da móvel',
    phase: 'Escopo',
    status: 'Em andamento',
    baseline: 'A definir',
    report: 'Em análise para possível abertura de projeto interno Claro.',
    farol: 'No prazo',
  },
  {
    id: '5',
    type: 'Melhoria',
    initiative: 'Combo Multi',
    code: 'C00003.14',
    name: 'Erro - Combo Multi - Nome do Bairro',
    phase: 'Escopo',
    status: 'Em andamento',
    baseline: 'A definir',
    report: 'Em análise para possível abertura de projeto interno Claro.',
    farol: 'No prazo',
  },
  {
    id: '6',
    type: 'Estruturante',
    initiative: 'Combo Multi',
    code: 'C00004',
    name: 'Migração Pré Controle COMBO MULTI',
    phase: 'Homologação Cliente',
    status: 'Impedimento',
    baseline: '26/01/2026',
    report: 'Aguardando definição da solução, se seguirá com RGC.',
    farol: 'Atrasado (Cliente)',
  },
  {
    id: '7',
    type: 'Estruturante',
    initiative: 'Melhorias de Portabilidade',
    code: 'C00032.1',
    name: '(Controle Fácil) - Bemobi',
    phase: 'Escopo',
    status: 'Em andamento',
    baseline: 'A definir',
    report: '',
    farol: 'No prazo',
  },
  {
    id: '8',
    type: 'Estruturante',
    initiative: 'SIV 3.0',
    code: 'C00033',
    name: 'Clara - Fluxo único de vendas',
    phase: 'Protótipo',
    status: 'Em andamento',
    baseline: 'A definir',
    report: '',
    farol: 'No prazo',
  },
  {
    id: '9',
    type: 'Estruturante',
    initiative: 'SIV 3.0',
    code: 'C00034',
    name: 'Melhoria do Fluxo Cross Cel para Oferta Combo Multi',
    phase: 'Protótipo',
    status: 'Em andamento',
    baseline: 'A definir',
    report: '',
    farol: 'No prazo',
  },
];
